# Generated by Django 3.2.3 on 2021-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre_noticia', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('id_noticia', models.IntegerField()),
            ],
        ),
    ]
