# Generated by Django 3.2.3 on 2021-06-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosNews', '0002_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
    ]
