# Generated by Django 3.2.3 on 2021-06-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosNews', '0003_noticia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
