# Generated by Django 3.2.3 on 2021-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosNews', '0004_auto_20210628_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='comentario',
            field=models.TextField(default='sin comentario', null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
