# Generated by Django 3.2.3 on 2021-07-07 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosNews', '0006_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
